version: '3.7'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 0000
    ports:
      - "27017:27017"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:0000@mongo:27017/
    ports:
      - "8080:8080"
    networks:
      - app-network
    command: ./main

volumes:
  mongo-data:

networks:
  app-network:
